### ISSUE TITLE
Multiple stroke orders support ?

### ISSUE THREAD

**Issue by hugolpz** [parsimonhi/animCJK#1]
As of 2018 : 

* Can AnimCJK handles multiple stroke orders variations ? `{PRC=default|t|j|k|h}` ?
  * PRC : yes : [/animCJK/svgsZhHans : 3,538 files](https://github.com/parsimonhi/animCJK/tree/master/svgsZhHans)
  * JA : yes : [/animCJK/svgsJa : 2,998 files](https://github.com/parsimonhi/animCJK/tree/master/svgsJa)
  * TW : no ?
  * HK : no but is it needed?
  * KO : no but is it needed?
2. Do you still need a list of radicals with their official stroke order per polity ? (I could complete [a comparative JA|CN|TW list](https://commons.wikimedia.org/wiki/Commons:Stroke_Order_Project/Kangxi_radicals/1-99) within a month)
  * Stroke order : maybe to kickstart Taiwanese stroke order ? ^^ We have solid source for that.
  * Glyphs shapes variations ? maybe needs review ?
3. What is your advancement on this front ? Is it done ?
  * See upper : JA = 2998 ; TW = 3538. :1st_place_medal: 

----
PS1: [According to Skishore](https://github.com/skishore/makemeahanzi/issues/1), it may be more relevant to propose multi-polities input you here.
PS2: I'am catching up with your projects and efforts, my apologizes for my many questions, but it's for greater good :+1:

[1]: Li, Xian (李鍌); al. (1995), [常用國字標準字體筆順手冊](http://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/BISHUEN/c8.htm) (ROC-Taiwan standard shapes and stroke orders of commonly used characters), Taiwan Ministry of Education, ISBN 957-00-7082-X (Authoritative)

**Comment by parsimonhi** [comment]
1) About PRC set: I will extend the current set to 7000 characters (the so-called "Commonly used hanzi") in the future (no idea when).
2) About radical comparison between JA/CN/TW: it is always interesting to have this kind of information. Each time I get a new source, I can reduce the risk of errors.
3) About the Taiwanese set (4808 characters), it is not just a question of collecting stroke order information. I have to build a significant number of characters (140 at the moment) that are not in Makemeahanzi. Also I have to modify glyphs of many others and to check all the characters one by one: a very long work. I don't expect to complete this task in the next months (not enough time).

**Comment by parsimonhi** [comment]
Now, you can follow the advancement of the work on the Taiwanese set at http://gooo.free.fr/animCJK/all.php (select the "http://gooo.free.fr/animCJK/all.php" radio input).

**Comment by parsimonhi** [comment]
Hanja are on their way too! (go to http://gooo.free.fr/animCJK/all.php and select the Hanja (Korea) radio input).

**Comment by hugolpz** [comment]
Muahahaha ! You have source for their stroke order ? :D

**Comment by parsimonhi** [comment]
As I said previously, i am interested by any sources so I can crossed them and avoid errors. I does a check with http://hanja.naver.com/ at the moment.

**Comment by parsimonhi** [comment]
I am also interested by sources on "traditional characters" used today in mainland China (when a traditional character is mixed with simplified characters), and "traditional characters" used in China before the simplification (i don"t know if there are differences between the two). I am also interested by sources for Hong-Kong, Singapour, Macao and Vietnam, but I don't intend to make the corresponding characters in the near future, so it is less important.

**Comment by hugolpz** [comment]
I will go in Taipei in June, I could get a hardcopy on the official reference for Taiwan. :smile: :+1: 
For others I don't really have access, I just pass by hk airport.

* The simplification pushed for alphabet-like horizontal writting so it changed some stroke order to be more convenient that way.
* So far, stating an "official" stroke order appeared in the 70s in Japan, 90s in Taiwan and China (80s?). 
* Afterwhat, I read that Emperial china had no ministry of education setting up kids' curriculum as of now. I know of some "wellknown" book with set of rules and correct samples of stroke order in Emperial China, but I never got my hands on them. 
* Even older, I examined the kangxi dictionary font longly. As well a Luoyang's steles one afternoon... even when Regular style is on it, one can guess the stroke order thanks to some volunteer hooks by the painters & sculpters.
* There are also traces on paints on 2000 years old silks, and on oracle bones. So one can also infer the author's stroke order.
But as we dig into time, we leave the era of normative stroke order and dive into "practice", common or particular to this writer. It becomes the study of One writer. As for teaching, learning and normalization, only the late century(ies?) provide authoritative resources. 

Funny inquiry. ^^

**Comment by parsimonhi** [comment]
Now, the svgsZhHans repository contains 7000 characters (instead of 3538), i.e. the "commonly used hanzi".
