### ISSUE TITLE
Can you help to download each character's animation in SVG files?

### ISSUE THREAD

**Issue by gentleahn** [parsimonhi/animCJK#10]
Hi author,
I'm really thanks to your project what i really want to.

As a non-developer, I want to download SVG files of each character on your project thus, can you tell me the way to get it?

Thank you very much in advance.

**Comment by edberteliezer** [comment]
There  is a green download code button in here : https://github.com/parsimonhi/animCJK Press download as zip. The SVGs are in the svgsKana svgsJa svgsJaSpecial and other svgs folders.
