### ISSUE TITLE
Incorrect draw for 給

### ISSUE THREAD

**Issue by tokyokamera** [parsimonhi/animCJK#11]
The kanji 給 has the following component: 糹 (糸)
糸: japanese
糹: chinese

**Comment by parsimonhi** [comment]
Are you sure of that? In kaisho style (楷書体) it seems that 糸 radical is written in Japanese as in Chinese (i.e. as 糹) when it is on the left side of the kanji. See for instance https://moji.tekkai.com/zoom/%E7%B5%A6/page.html or https://kakijun.jp/page/12180200.html

Do you have a reference where it is written 糸 on the left side of the kanji in kaisho style?

**Comment by tokyokamera** [comment]
Thanks for your info.
I confused about writing style of Kanji.
<img src="http://img.kakijun.com/kanjiphoto/gif/7d66.gif"/>
<img src="http://img.kakijun.com/kanjiphoto/frame/7cf8_frames.png"/>
