### ISSUE TITLE
Generate repository with -red.svg files

### ISSUE THREAD

**Issue by hugolpz** [parsimonhi/animCJK#12]
Hi there, I recently attacked Wikimedia Commons' bot coding, and my bot now under review so I can resume our 2018 discussion.

Could you generate a directory of your red svg, while specifying your stylesheet, inspired from Commons stroke order Project, is also under open license, CC-by or PD, as you prefer.

This requests follows [this conversation](https://github.com/skishore/makemeahanzi/issues/25).

**Comment by parsimonhi** [comment]
Hello,

Do you need some help?

**Comment by hugolpz** [comment]
Hello @Parsimonhi. For now i am rolling in shame that i missed that imageFactory for 2.5 years. But Yes, will need some help on styles hacking. I have to double check our Commons styles first tho.

**Comment by parsimonhi** [comment]
About 羊:
1) 羊 is the same in zhHans and ja.

2) even if a character is exactly the same in both zhHans and ja, it is present in both repositories, because it is simpler for people who are interested in only one language to get all the characters of this language in one move.
