### ISSUE TITLE
Redirecting wikipedians toward MMAH/AnimCJK

### ISSUE THREAD

**Issue by hugolpz** [parsimonhi/animCJK#14]
@Parsimonhi, @Skishore, thank you for your two projects which are wonderful pieces for learning Eastern Asian languages.

Your duo of projects are clearly superseding Wikimedia Commons' Stroke Order project which I initiated in 2005.

Also, I made some edit to redirect willing wikimedia contributors toward MMAH and AnimCJK projects. This suggestion is now on our central Stroke Order template, [{SOlicense}](https://commons.wikimedia.org/wiki/Template:SOlicense). It is therefore displayed on ALL of our 2,000+ hand-drawn stroke order images, used accross wikimedia projects and beyond. It's first draft and discrete, but it's there. And you can edit the template (I think), or suggest me new edits.

![Screenshot_2021-04-23_21-23-35](https://user-images.githubusercontent.com/1420189/115920235-3198e080-a47a-11eb-9ef4-be0a5d86e19c.png)

If you have a landing page to receive new contributors, please share it to me. So I may share it with the wikimedia community.
I do not expect much contributors in such niche projects and github-hosted project. But once in a while, one wikimedian may land on your github project to contribute a bit. Transformation into MMAH/AnimCJK contributor will be higher if they land first on a clear Howto/Todo page, easing on-boarding.

**Comment by parsimonhi** [comment]
Thanks for your add. It is ok for me.
