### ISSUE TITLE
Possible error in graphicsJa

### ISSUE THREAD

**Issue by cademcniven** [parsimonhi/animCJK#16]
I wanted to convert graphicsJa from jsonl to json (which I did using jq), but got an error:

"parse error: Invalid numeric literal at line 1011, column 2892"

which is for the character 抽. The conversion worked fine after deleting that line though. I'm not sure exactly what the issue is, but it's possible that the data for that kanji is bad, so just giving you a heads up.

**Comment by parsimonhi** [comment]
You are right. There is an error in the data for the character 抽.

You can fix the error manually by removing the "[C,858,334],[840,211]," string from graphicsJa.txt.

I will correct the data in the next update.

**Comment by parsimonhi** [comment]
I updated the master to fix this error.
