### ISSUE TITLE
Could you add the following characters in graphicsJa.txt ?

### ISSUE THREAD

**Issue by p0ker-fACE** [parsimonhi/animCJK#18]
I sincerely am in fond of your project. However, because I'm using a kanji deck on anki (https://ankiweb.net/shared/info/1558868613) which uses your svg files for the production cards (where a frame appears on the front card and you need to draw the character correctly to get the answer right), there are twelve characters (namely: 篭, 罠, 囁, 呟,醤, 噛, 梱, 塡, 繍, 繋, 壷, 覗) for which no matter how hard I try I can't find their svg files. Can you please add/make their svg files as well? Thank you!

**Comment by parsimonhi** [comment]
Thank you for your support.

I will add them in the next update.

**Comment by p0ker-fACE** [comment]
> Thank you for your support.
> 
> I will add them in the next update.

Glad to hear that!

**Comment by parsimonhi** [comment]
Done!
