### ISSUE TITLE
Wrong stroke order number

### ISSUE THREAD

**Issue by MightyCoderX** [parsimonhi/animCJK#22]
4 is displayed instead of 3
![image](https://user-images.githubusercontent.com/36588044/173685690-bee0d7da-c846-410b-94d2-bc4661b5e9a2.png)

Edit:
There are also extra points in some characters
![image](https://user-images.githubusercontent.com/36588044/173777041-a0c63ca5-60fc-4322-ac83-870a7982298e.png)

**Comment by parsimonhi** [comment]
Thanks for your report. This will be fixed in the next update.

**Comment by parsimonhi** [comment]
Just fixed the bug.
