### ISSUE TITLE
乾 = traditional character ( Also, including 傳承字 in dictionaryZhHant.txt )

### ISSUE THREAD

**Issue by lxs602** [parsimonhi/animCJK#23]
Hi, 

You have 乾 listed in dictionaryZhHans.txt as HSK level 7

I cannot find 乾 in [HSK (v3) 2021](https://github.com/shawkynasr/HSK-official-Query-System)

I  understand that 乾 is a traditional character, and the simplified form is 干 .

Should this be listed in  dictionaryZhHant.txt instead?

L

**Comment by lxs602** [comment]
Also, many characters in  dictionaryZhHans.txt are inherited forms ( 傳承字 / 传承字 )

These could also be included in dictionaryZhHans.txt as they are not simplified

**Comment by parsimonhi** [comment]
Hello,

1) AnimCJK still uses HSK (v2) 2010 lists. HSK7 just means that the character is not in HSK1 to HSK6 (v2) 2010, but is in the "Frequently Used Characters" list. And HSK8 means that the character is not in HSK1 to HSK7, but is in the "Commonly used characters" list. I will update AnimCJK one day to take into account HSK (v3) 2021. But i don't know when.

2) 乾 is special. It has a simplified form 干 when it means "dry", but it is not simplified when it means "first of the eight trigrams (bagua) used in Taoist cosmology" (see https://en.wiktionary.org/wiki/%E4%B9%BE). In this case, both simplified and traditional characters are 乾. It is not in the HSK (vs) 2010 list. But it is in the "Frequently Used Characters" list. As a result, it appears in dictionaryZhHans.txt as HSK7.

3) The dictionaryZhHant.txt contains only some traditional characters. It is far from to be finished. This is why it doesn't contain 乾.

**Comment by lxs602** [comment]
1. Ok. I believe HSKv3 was scheduled for this year, but has not been officially released yet.
2. Your language skills seem much better than mine. I am only a beginner, so thanks for the information.
3. Just a suggestion... no problems.
Best wishes, L
