### ISSUE TITLE
How to automatically restart animation after it finished

### ISSUE THREAD

**Issue by UEPSs** [parsimonhi/animCJK#24]
I find stroke order animations stop after finishing playing. How to make them to auto restart? In other words, how to make animations auto repeat?

**Comment by parsimonhi** [comment]
It depends of the context.

**Comment by parsimonhi** [comment]
It depends of the context.

How are you using animCJK?

**Comment by UEPSs** [comment]
> It depends of the context.
> 
> How are you using animCJK?

I use it in android WebView.

**Comment by parsimonhi** [comment]
I meant, do you just display the svg files where the characters are stored in your android WebView? Or do you insert these svg files inside a html page and display this html page in your android WebView?

Making an auto-repeat needs modifying the css of each svg files one by one, or alternately can be done with some javascript codes that can be inserted in the svg files or in a web page that displays the svg files.

A sample of the later case is visible at http://gooo.free.fr/animCJK/official/samples/ (select the "infinite" radio button, then click on "display"). But it needs some adaptation (depend what you are doing exactly).
