### ISSUE TITLE
JP 27595.svg format?

### ISSUE THREAD

**Issue by HHHHHHHHHHHHHHHHHHHHHCS** [parsimonhi/animCJK#25]
<clipPath id="z27595c1"><use xlink:href="#z27595d1"/></clipPath>
	<clipPath id="z27595c2"><use xlink:href="#z27595d2"/></clipPath>
	<clipPath id="z27595c3"><use xlink:href="#z27595d3"/></clipPath>
	<clipPath id="z27595c4"><use xlink:href="#z27595d4"/></clipPath>

<path style="--d:1s;" pathLength="3333" clip-path="url(#z27595c1)" d="M307 152L345 217L340 265L238 623L248 647L722 638L869 691"/>
<path style="--d:2s;" pathLength="3333" clip-path="url(#z27595c2)" d="M366 174L408 185L627 144L697 190L659 595L613 785L558 879L450 818"/>
<path style="--d:3s;" pathLength="3333" clip-path="url(#z27595c3)" d="M 480,195 515,242 441,610"/>
<path style="--d:4s;" pathLength="3333" clip-path="url(#z27595c4)" d="M71 438L138 449L816 385L927 402"/><defs>
</defs>

def and /def maybe need move position ?

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
<clipPath id="z27595c1"><use xlink:href="#z27595d1"/></clipPath>
	<clipPath id="z27595c2"><use xlink:href="#z27595d2"/></clipPath>
	<clipPath id="z27595c3"><use xlink:href="#z27595d3"/></clipPath>
	<clipPath id="z27595c4"><use xlink:href="#z27595d4"/></clipPath>

<path style="--d:1s;" pathLength="3333" clip-path="url(#z27595c1)" d="M307 152L345 217L340 265L238 623L248 647L722 638L869 691"/>
<path style="--d:2s;" pathLength="3333" clip-path="url(#z27595c2)" d="M366 174L408 185L627 144L697 190L659 595L613 785L558 879L450 818"/>
<path style="--d:3s;" pathLength="3333" clip-path="url(#z27595c3)" d="M 480,195 515,242 441,610"/>
<path style="--d:4s;" pathLength="3333" clip-path="url(#z27595c4)" d="M71 438L138 449L816 385L927 402"/><defs>
</defs></svg>

changed:

<defs>
	<clipPath id="z27595c1"><use xlink:href="#z27595d1"/></clipPath>
	<clipPath id="z27595c2"><use xlink:href="#z27595d2"/></clipPath>
	<clipPath id="z27595c3"><use xlink:href="#z27595d3"/></clipPath>
	<clipPath id="z27595c4"><use xlink:href="#z27595d4"/></clipPath>
</defs>
....

**Comment by parsimonhi** [comment]
Why?

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
Oh sorry, it's work. Only format Misalignment. 
Look       def /def

usual:

```xml

<defs>
	<clipPath id="z27595c1"><use xlink:href="#z27595d1"/></clipPath>
	<clipPath id="z27595c2"><use xlink:href="#z27595d2"/></clipPath>
	<clipPath id="z27595c3"><use xlink:href="#z27595d3"/></clipPath>
	<clipPath id="z27595c4"><use xlink:href="#z27595d4"/></clipPath>
</defs>

```

JP 27595.svg:

```xml

<path id="z27595d4" d="M288 413C220 418 150 423 78 430C63 431 60 437 71 449C80 459 91 466 104 470C118 474 131 475 142 473C185 462 231 452 280 446C311 442 311 442 327 440C359 435 406 431 466 426C496 423 496 423 511 422C552 418 599 418 650 418C689 417 689 417 708 417C747 416 790 417 836 419C893 421 925 419 930 413C934 405 930 395 919 386C881 355 841 347 799 356C772 361 743 364 712 369C672 374 672 374 652 377C609 382 564 388 516 393C486 396 486 396 471 397C426 400 381 405 335 409C304 412 304 412 288 413Z"/>
	<clipPath id="z27595c1"><use xlink:href="#z27595d1"/></clipPath>
	<clipPath id="z27595c2"><use xlink:href="#z27595d2"/></clipPath>
	<clipPath id="z27595c3"><use xlink:href="#z27595d3"/></clipPath>
	<clipPath id="z27595c4"><use xlink:href="#z27595d4"/></clipPath>

<path style="--d:1s;" pathLength="3333" clip-path="url(#z27595c1)" d="M307 152L345 217L340 265L238 623L248 647L722 638L869 691"/>
<path style="--d:2s;" pathLength="3333" clip-path="url(#z27595c2)" d="M366 174L408 185L627 144L697 190L659 595L613 785L558 879L450 818"/>
<path style="--d:3s;" pathLength="3333" clip-path="url(#z27595c3)" d="M 480,195 515,242 441,610"/>
<path style="--d:4s;" pathLength="3333" clip-path="url(#z27595c4)" d="M71 438L138 449L816 385L927 402"/><defs>
</defs>

```

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
Thank you for your fixed
