### ISSUE TITLE
Missing decomposition/acjk for 览

### ISSUE THREAD

**Issue by bendyorke** [parsimonhi/animCJK#27]
I am not sure if this is intended/expected, but the decomposition/acjk data for the character `览` is:

```
{
  "character":"览",
  "set":["hsk5"],
  "definition":"look at, inspect; perceive",
  "pinyin":["lǎn(48)"],
  "radical":"见 (見)",
  "decomposition":"⿱见",
  "acjk":"览⿱5见.4"
}
```

I think this is an error, as I believe it is the only decomposition/acjk that has a stroke count following a character split

**Comment by parsimonhi** [comment]
You are right. It is an error. I just updated the master.

Thanks for your report.
