### ISSUE TITLE
Glyphs for 轆轤 missing

### ISSUE THREAD

**Issue by LoekvanKooten** [parsimonhi/animCJK#31]
The glyphs for 36678 and 36708 seem to be missing.

**Comment by parsimonhi** [comment]
animCJK contains about 10000 characters (the most common). But there are more than 50000 characters referenced in unicode. As a result, there are of course many characters that are missing.

In what language do you need 轆 and 轤? Japanese?

**Comment by LoekvanKooten** [comment]
I totally understand! Yes, Japanese indeed.

Of course I don't know how much work this is for you, but assuming you want to constantly extend this set, this seems like a lifework that will never end.

I'm just passing on missing characters as soon as I encounter them.

**Comment by parsimonhi** [comment]
I see :-)

I will add these two characters soon.

Adding a new character takes about 30 minutes.

**Comment by parsimonhi** [comment]
Done!

**Comment by LoekvanKooten** [comment]
Thanks a lot!
