### ISSUE TITLE
膵 missing

### ISSUE THREAD

**Issue by LoekvanKooten** [parsimonhi/animCJK#33]
I noticed another missing character in Japanese.

If there's any way I can help to create these, let me know. Though I can understand if you want to keep the process secret, of course.

**Comment by parsimonhi** [comment]
Hi,

I just updated the master (add 膵 in svgsJa).

There is nothing secret in the process. It is just not simple to explain it in details.

Basically there are 3 cases:
1) The character is in the makeMeAHanzi project
- I retrieve the data from the makeMeAhanzi graphics.txt file.
- I use a script to transform the data into animCJK format.
2) The character is not in the makeMeAhanzi project, but in one of the Arphic fonts
- I make a svg file with a text editor that contains a text tag displaying the character with one of the Arphic font.
- I open it with Inkscape.
- I transform the outline of the character into a path (Inkscape has a menu to do that).
- I cut the path into several paths (one per stroke).
- I use some regex to transform the resulting Inkscape svg file into animCJK format.
3) The character is not in the makeMeAhanzi project nor in Arphic fonts
- I look for other characters that have a component (or at least some strokes) in common with the character.
- I build a new svg with these components using a text editor. I adapt each stroke shape and size with Inkscape.
- I use some regex to transform the resulting Inkscape svg file into animCJK format.

In all cases:
- I use Inkscape and/or a text editor to correct any errors (stroke shape and stroke order), take into account the differences between languages (makeMeAHanzi is only for zhHans) and improve the character shape (there are many small defects in Arphic fonts, and makeMeAHanzi got its data from Arphic fonts using a semi-automatic process without fixing them).
- I use a script to add a brush effect at the end of each stroke that ends on another stroke.
- I use a script to optimize the medians
- I use a script to update the graphicsXxx.txt file
- I use a script to update the dictionaryXxx.txt file (Xxx is Ja, Ko, ZhHans or ZhHant).
- I update the master on github and the demo site.

Scripts are in php and javascript. They are not trivial. You can find some of these scripts in animCJK repository (see the main folder and the sample folder).

**Comment by LoekvanKooten** [comment]
Thank you very much for adding the character and the very extensive explanation. Not an easy process it seems. I wish there was a way to alleviate your workload, but before I'd be able to add any value you'd have produced dozens of characters yourself already. Do you accept donations?

**Comment by parsimonhi** [comment]
I don't need money. Your support is enough for me. :-)
