### ISSUE TITLE
Wrong stroke order for Japanese 昇

### ISSUE THREAD

**Issue by MagisterAdamus** [parsimonhi/animCJK#34]
The Japanese kanji 昇 has the wrong stroke order, with the sixth and seventh strokes reversed.

References:
* https://kakijun.jp/page/08144200.html
* http://kakijun.com/c/6607.html
* http://db.yamasa.org/ocjs/kanjidic.nsf/SortedByKanji2THEnglish/%E6%98%87?OpenDocument

**Comment by parsimonhi** [comment]
Hi,

Thank for your report. You are right. I fixed it and just updated the master.
