### ISSUE TITLE
Fix for ま animation

### ISSUE THREAD

**Issue by EasySigh** [parsimonhi/animCJK#35]
- Path /svgsKana/12414.svg
- Line 43

`<path style="--d:3.8s;" pathLength="3333" clip-path="url(#z12414c3b)" d="M273 840L310 775L400 763L759 885L792 929"/>`

**Comment by parsimonhi** [comment]
Hi,

Thank for your fix. I just updated the master, but i put another fix to be more consistent with other kanas that have overlapped strokes.
