### ISSUE TITLE
Any method to draw strokes with python instead of web page?

### ISSUE THREAD

**Issue by nissansz** [parsimonhi/animCJK#36]
Any method to draw strokes with python instead of web page?

**Comment by parsimonhi** [comment]
Hi,

Character shapes are stored in SVG files (see svgsJa, svgsKo, svgsZhHans ... ). And svg files are text files. So you can read these files with a Python script and view them as you would any SVG file. The method depends of your context (what python modules are you using to display something, and what you want to do with animCJK).
