### ISSUE TITLE
Maybe small correction for hiragana su す and zu ず?

### ISSUE THREAD

**Issue by TiboSM** [parsimonhi/animCJK#40]
Hi,

Thank you so much for the huge work done on this. This is amazing.

The hiragana for す has a strange 90° angle before the loop, which seems to be misleading for people learning how to write it. Am I wrong?

**Comment by parsimonhi** [comment]
Hi,

It's a matter of style. And the angle is usually there even though you usually don't see it because it's behind the end of the stroke. But you're right, it can be confusing for beginners.

So I modified す and ず and updated the master.
