### ISSUE TITLE
令 is wrong in Japanese

### ISSUE THREAD

**Issue by Kimeiga** [parsimonhi/animCJK#41]
shows the chinese version when japanese is selected. 

<img width="598" alt="image" src="https://github.com/parsimonhi/animCJK/assets/20587215/f9c43fb7-3905-41f4-b5c9-5bdffa7c87b9">

Should show something more like the following korean version:

<img width="556" alt="image" src="https://github.com/parsimonhi/animCJK/assets/20587215/5bc4f0bc-22d5-405e-8026-c7e06a974a71">

chinese version for reference:

<img width="572" alt="image" src="https://github.com/parsimonhi/animCJK/assets/20587215/b745aa2b-00a2-45ea-9b13-e22cabf76e1b">

[confirmation from Wiktionary:](https://en.wiktionary.org/wiki/%E4%BB%A4)

<img width="114" alt="image" src="https://github.com/parsimonhi/animCJK/assets/20587215/5475c3b1-f036-4dba-81de-bbc30a73c6af">

(and one of my japanese friends)

beautiful project btw; thank you :)

**Comment by diceoh** [comment]
See here - that style is the standard Kyokasho style taught in Japanese schools for handwriting. What's shown on the Wikipedia page is the standard gothic-style print font, which can differ from the handwritten style.
https://kanji.jitenon.jp/kanjib/632.html

**Comment by Kimeiga** [comment]
thank you! learned something new
